language: node_js
node_js: 10
after_success:
- chmod 600 ~/.ssh/id_rsa   #还是Linux文件权限问题
- ssh root@47.95.209.77 -o StrictHostKeyChecking=no 'cd /home/vueDemo && git pull && npm install && npm run build'   #使用ssh连接服务器
before_install:
- openssl aes-256-cbc -K $encrypted_230e5c0978d4_key -iv $encrypted_230e5c0978d4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d