language: node_js
node_js:
- '10'
addons:
  ssh_known_hosts:
  - 47.95.209.77
before_install:
- openssl aes-256-cbc -K $encrypted_230e5c0978d4_key -iv $encrypted_230e5c0978d4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- ssh root@47.95.209.77 -o StrictHostKeyChecking=no 'cd /home/vueDemo && git pull
  && npm install && npm run build'
