language: node_js
node_js:
- '10'
addons:
  ssh_known_hosts:
  - 47.95.209.77
before_install:
ls -l ~/.ssh/
- openssl aes-256-cbc -K $encrypted_09d97a7e586a_key -iv $encrypted_09d97a7e586a_iv
  -in id_rsa_vue.enc -out /home/travis/.ssh/id_rsa_vue -d
- chmod 600 ~/.ssh/id_rsa_vue
- echo -e "47.95.209.77\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- ll
