language: node_js
node_js:
- '10'
addons:
  ssh_known_hosts:
  - 47.95.209.77
before_install:
- ls -l ~/.ssh/
- cat ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_09d97a7e586a_key -iv $encrypted_09d97a7e586a_iv
  -in id_rsa_vue.enc -out ~/.ssh/id_rsa_vue -d
- chmod 600 ~/.ssh/id_rsa_vue
after_success:
- ssh root@47.95.209.77 -o StrictHostKeyChecking=no 'cd /home/vueDemo && git pull && npm install && npm run build'   #使用ssh连接服务器
