language: node_js
node_js:
- '10'
addons:
  ssh_known_hosts:
  - 47.95.209.77
before_install:
- chmod 600 ~/.ssh/id_rsa
- openssl aes-256-cbc -K $encrypted_6d66a5d31f8a_key -iv $encrypted_6d66a5d31f8a_iv
  -in id_rsa_vue.pub.enc -out ./id_rsa_vue.pub -d
after_success:
- ssh travis@47.95.209.77 -o StrictHostKeyChecking=no 'cd /home/vueDemo && git pull
  && npm install && npm run build'
