language: node_js
node_js:
- '10'
addons:
  ssh_known_hosts:
  - chenming.club
before_install:
- openssl aes-256-cbc -K $encrypted_09d97a7e586a_key -iv $encrypted_09d97a7e586a_iv
  -in id_rsa_blog.enc -out ~/.ssh/id_rsa_blog -d
- chmod 600 ~/.ssh/id_rsa_blog
- echo -e "Host chenming.club\n\tHostName 47.95.209.77\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/id_rsa_blog" >> ~/.ssh/config
install:
- yarn install
script:
- yarn build
after_success:
- ssh root@chenming.club -o StrictHostKeyChecking=no 'rm -rf /home/vue-demo/vue-demo/dist/*'
- scp -o stricthostkeychecking=no -r ./dist root@chenming.club:/home/vue-demo/vue-demo
- scp -o stricthostkeychecking=no -r ./server/* root@chenming.club:/home/laravel-docker/project/project/webssh
- ssh root@chenming.club -o StrictHostKeyChecking=no 'cd /home/vue-demo && docker-compose up -d --build && cd /home/laravel-docker/project/project/webssh && docker-compose up -d'   #使用ssh连接服务器
