language: node_js
node_js:
- '10'
addons:
  ssh_known_hosts:
  - 47.95.209.77
before_install:
- openssl aes-256-cbc -K $encrypted_6d66a5d31f8a_key -iv $encrypted_6d66a5d31f8a_iv
  -in id_rsa_vue.pub.enc -out ./id_rsa_vue.pub -d
- cat ~/.ssh/config
- chmod 600 ~/.ssh/id_rsa_vue
- echo -e "47.95.209.77\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- ll
