# FROM nginx

# WORKDIR /usr/src/app/

# COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

# COPY ./dist  /usr/share/nginx/html/

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]

FROM nginx:alpine

COPY ./ /var/www/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
WORKDIR /var/www/html
