version: '3.5'

services:
  # 线上打包 测试的 服务
  # vue_demo_pro_web:
  #   build: ../
  #   container_name: 'vue_demo_pro_web'
  #   volumes:
  #     - dist:/usr/src/app/dist

  nginx_server:
    image: nginx:alpine
    ports:
      - 981:80
    restart: unless-stopped
    volumes:
      - ./upstream.conf:/etc/nginx/conf.d/default.conf

  vue_demo_server:
    build: ../
    # ports:
    #   - 981:80
    # container_name: 'vue_demo_server'
    restart: unless-stopped
    # volumes:
      # - dist:/usr/share/nginx/html:ro
      # - ../dist:/usr/share/nginx/html:ro
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf

# volumes:
#   dist:
