version: '3.5'

services: 

  term_webscoket_server:
    build: .
    restart: unless-stopped
    ports: 
      - "6002:9999"
    networks:
      - nginx_net
  
networks:
  nginx_net:
    external: true
