export { default as CTable } from './CTable/index.vue'
export { default as CPagination } from './CPagination/index.vue'
export { default as CForm } from './CForm/index.vue'
export { default as SearchArea } from './SearchArea/index.vue'
export { default as CUpload } from './CUpload/index.vue'
